/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fruteria.ui.app.views;

import fruteria.ui.app.controller.ClientsController;
import fruteria.ui.app.model.Client;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author kdieg
 */
public class ClientsMaintainer extends javax.swing.JFrame {
  private final String IMAGES_PATH = "src\\fruteria\\ui\\app\\assets\\images";
  /**
   * Creates new form ClientsMaintainer
   */
  public ClientsMaintainer() {
    initComponents();
    setLocationRelativeTo(this);
  }
  
  public void listClients(){
    areaList.setText("");
    for(Client fruit:ClientsController.getClients()){
      areaList.append(fruit.toString() + "\n");
    }
  }
  
  public void clearInputs(){
    txtRut.setText(null);
    txtName.setText(null);
    txtEnterprise.setText(null);
    txtAddress.setText(null);
    txtLogo.setText(null);
    stxPhoto.setIcon(null);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel8 = new javax.swing.JLabel();
    txtRut = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    txtName = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    txtEnterprise = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    txtAddress = new javax.swing.JTextField();
    jLabel7 = new javax.swing.JLabel();
    txtLogo = new javax.swing.JTextField();
    stxPhoto = new javax.swing.JLabel();
    btnCreate = new javax.swing.JButton();
    btnFind = new javax.swing.JButton();
    btnEdit = new javax.swing.JButton();
    btnDelete = new javax.swing.JButton();
    btnList = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    areaList = new javax.swing.JTextArea();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jLabel8.setText("Mantenedor de Clientes");

    jLabel1.setText("RUT:");

    jLabel2.setText("NOMBRE:");

    jLabel3.setText("EMPRESA:");

    jLabel5.setText("DIRECCION: ");

    jLabel7.setText("IMAGEN:");

    stxPhoto.setText("                         FOTO");
    stxPhoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

    btnCreate.setBackground(new java.awt.Color(0, 204, 0));
    btnCreate.setText("Crear");
    btnCreate.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCreateActionPerformed(evt);
      }
    });

    btnFind.setBackground(new java.awt.Color(153, 153, 255));
    btnFind.setText("Buscar");
    btnFind.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnFindActionPerformed(evt);
      }
    });

    btnEdit.setBackground(new java.awt.Color(255, 153, 0));
    btnEdit.setText("Editar");
    btnEdit.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnEditActionPerformed(evt);
      }
    });

    btnDelete.setBackground(new java.awt.Color(255, 0, 0));
    btnDelete.setText("Eliminar");
    btnDelete.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnDeleteActionPerformed(evt);
      }
    });

    btnList.setBackground(new java.awt.Color(153, 153, 255));
    btnList.setText("Listar");
    btnList.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnListActionPerformed(evt);
      }
    });

    areaList.setColumns(20);
    areaList.setRows(5);
    jScrollPane1.setViewportView(areaList);

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(122, 122, 122)
            .addComponent(jLabel8))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addComponent(jLabel1)
                      .addComponent(jLabel2)
                      .addComponent(jLabel3)))
                  .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel5)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(4, 4, 4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                      .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                      .addComponent(txtEnterprise)
                      .addComponent(txtRut)))
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(45, 45, 45)
            .addComponent(stxPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jScrollPane1)
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnCreate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFind)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(btnList)))))
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(11, 11, 11)
        .addComponent(jLabel8)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(jLabel1)
                  .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jLabel2))
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jLabel3))
              .addComponent(txtEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel5))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(txtLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel7)))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(stxPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGap(29, 29, 29)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(btnList)
          .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(btnCreate)
            .addComponent(btnFind)
            .addComponent(btnEdit)
            .addComponent(btnDelete)))
        .addGap(14, 14, 14)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
    // TODO add your handling code here:
    String rut, name, enterprise, address, logo;
    Client client = null;

    if(!txtRut.getText().equals("")
      &&!txtName.getText().equals("")
      && !txtEnterprise.getText().equals("")
      && !txtAddress.getText().equals("")
      && !txtLogo.getText().equals("")){
      //
      rut = txtRut.getText();
      name = txtName.getText();
      enterprise = txtEnterprise.getText();
      address = txtAddress.getText();
      logo = txtLogo.getText();
      client = new Client(rut, name, enterprise, address, logo);

      if(ClientsController.create(client)){
        clearInputs();
        listClients();
        JOptionPane.showMessageDialog(null, "Cliente Creado Correctamente", "Crear Cliente", JOptionPane.INFORMATION_MESSAGE);
      }else{
        JOptionPane.showMessageDialog(null, "Error al crear Cliente", "Crear Cliente", JOptionPane.ERROR_MESSAGE);
      }
    }else{
      JOptionPane.showMessageDialog(null, "Complete todos los campos ", "Crear Cliente", JOptionPane.WARNING_MESSAGE);
    }

  }//GEN-LAST:event_btnCreateActionPerformed

  private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
    // TODO add your handling code here:
    String rut;
    Client client;
    if(!txtRut.getText().equals("")){
      rut = txtRut.getText();
      client = ClientsController.show(rut);

      if(client != null){
        txtRut.setText(client.getRut());
        txtName.setText(client.getName());
        txtEnterprise.setText(client.getEnterprise());
        txtAddress.setText(String.valueOf(client.getAddress()));
        txtLogo.setText(client.getLogo());
        stxPhoto.setIcon(new ImageIcon(IMAGES_PATH + "\\clients\\"+ client.getLogo()));
        JOptionPane.showMessageDialog(null, "Cliente encontrado", "Buscar", JOptionPane.INFORMATION_MESSAGE);
      }else{
        JOptionPane.showMessageDialog(null, "Cliente no encontrado", "Buscar", JOptionPane.INFORMATION_MESSAGE);
      }
    }else{
      JOptionPane.showMessageDialog(null, "Debe Ingresar Rut", "Buscar", JOptionPane.WARNING_MESSAGE);
    }
  }//GEN-LAST:event_btnFindActionPerformed

  private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
    // TODO add your handling code here:
    String rut, name, enterprise, address, logo;
    Client client = null;

    if(!txtRut.getText().equals("")
      && !txtName.getText().equals("")
      && !txtEnterprise.getText().equals("")
      && !txtAddress.getText().equals("")
      && !txtLogo.getText().equals("")){
      //
      rut = txtRut.getText();
      name = txtName.getText();
      enterprise = txtEnterprise.getText();
      address = txtAddress.getText();
      logo = txtLogo.getText();
      client = new Client(rut, name, enterprise, address, logo);

      if(ClientsController.update(client)){
        clearInputs();
        listClients();
        JOptionPane.showMessageDialog(null, "Cliente Editado Correctamente", "Editar Cliente", JOptionPane.INFORMATION_MESSAGE);
      }else{
        JOptionPane.showMessageDialog(null, "Error al Editar Cliente"
          + "", "Editar Cliente", JOptionPane.ERROR_MESSAGE);
      }
    }else{
      JOptionPane.showMessageDialog(null, "Complete todos los campos ", "Editar Cliente", JOptionPane.WARNING_MESSAGE);
    }

  }//GEN-LAST:event_btnEditActionPerformed

  private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
    // TODO add your handling code here:

    String rut;
    if(!txtRut.getText().equals("")){
      //
      rut = txtRut.getText();
      if(ClientsController.delete(rut)){
        clearInputs();
        listClients();
        JOptionPane.showMessageDialog(null, "Cliente Eliminado", "Eliminar Cliente", JOptionPane.INFORMATION_MESSAGE);
      }else{
        JOptionPane.showMessageDialog(null, "Error al Eliminar Cliente", "Eliminar Cliente", JOptionPane.ERROR_MESSAGE);
      }
    }else{
      JOptionPane.showMessageDialog(null, "Debe ingresar ID de Cliente", "Eliminar Cliente", JOptionPane.WARNING_MESSAGE);
    }
  }//GEN-LAST:event_btnDeleteActionPerformed

  private void btnListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListActionPerformed
    // TODO add your handling code here:
    listClients();
  }//GEN-LAST:event_btnListActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(ClientsMaintainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(ClientsMaintainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(ClientsMaintainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(ClientsMaintainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new ClientsMaintainer().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextArea areaList;
  private javax.swing.JButton btnCreate;
  private javax.swing.JButton btnDelete;
  private javax.swing.JButton btnEdit;
  private javax.swing.JButton btnFind;
  private javax.swing.JButton btnList;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JLabel stxPhoto;
  private javax.swing.JTextField txtAddress;
  private javax.swing.JTextField txtEnterprise;
  private javax.swing.JTextField txtLogo;
  private javax.swing.JTextField txtName;
  private javax.swing.JTextField txtRut;
  // End of variables declaration//GEN-END:variables
}
